### PR TITLE
added getOr

### PR DESCRIPTION
**Pull request by jheiling**

### CODE REVIEW

**Comment by jheiling** [comment]
I think the meaning of of `getOr` is pretty clear, but I agree it would make sense to name it in a way that matches `Maybe.withDefault`.
I would vote for `getWithDefault`.
The idea of having a `?` operator is great. It should be in the core libraries. If it was, I think it wouldn't even make sense to have this function.
Btw, is there a reason you don't have an `isJust` function in the elm-maybe-extra package?

**Comment by rehno-lindeque** [comment]
> The idea of having a ? operator is great. It should be in the core libraries. If it was, I think it wouldn't even make sense to have this function.

I wonder if there's some way to vote on this, there seems to be an overwhelming majority of people that want `(?)`. Perhaps I'll just tag @evancz as a crude voting mechanism! :D

I'd like to encourage people at our startup to use it instead of defining new functions. Do you feel strongly about `getWithDefault`?

> Btw, is there a reason you don't have an isJust function in the elm-maybe-extra package?

No reason, I published an update for you quickly: [isJust](http://package.elm-lang.org/packages/circuithub/elm-maybe-extra/latest/Maybe-Extra#isJust)

**Comment by jheiling** [comment]
Thanks!
I don't, I would prefer using `?` as well. It might make sense to have this function for people who don't want to add a dependency on elm-maybe-extra, but I don't think it's really important.

**Comment by evancz** [comment]
@rehno-lindeque, I am making all the non-total functions in core return `Maybe` so we'll have things like this:

```elm
head : List a -> Maybe a
```

As a result, I am planning to add the following function to `Maybe` because I know people will write it anyway:

```elm
Maybe.unsafe : Maybe a -> a
```

Which means you could write things like this:

```elm
unsafe (get "tom" peopleDict)
unsafe (head [1,2,3])
```

So you are explicitly tagging it as unsafe and no one using the function has any confusion about the risks they are taking.

I think `(?)` is cool, but I still do not know what precedence it should have. This is part of why I am not adding it, though another part is wanting to avoid having so many operators. In any case, I'd say add it to your library and try to figure out the right precedence. It is unclear to me how it should relate to `(|>)` and `(+)` and `(||)` etc.

**Comment by rehno-lindeque** [comment]
Thanks for the detailed response @evancz! I didn't mean to take up so much of your attention. I reckoned I'd create an issue in core so that others can comment. Best I can offer is that the default operator precedence seems to work pretty well, but I've hardly tried every situation where it would be used.

**Pull request closed without merging**
